### ISSUE TITLE
Linux: error when trying to generate audio with Bark

### ISSUE THREAD

**Issue by vuaieo** [tin2tin/Generative_AI#15] opened 2023-05-25 06:00 UTC
hio i tryed audio model card : AudioLDM S Full v2 but the sound generated wasnt so good and so then wanted try Bark but this gives me this error so not working. 

WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1337 pyrna_enum_to_py: current value '0' matches no enum in 'CharMorphUIProps', '', 'rig'
Downloading: "https://dl.fbaipublicfiles.com/encodec/v0/encodec_24khz-d7cc33bc.th" to /home/vuaieo/.cache/torch/hub/checkpoints/encodec_24khz-d7cc33bc.th
Traceback (most recent call last):
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.0/scripts/addons/Generative_AI-main/__init__.py", line 802, in execute
    preload_models(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 330, in preload_models
    _ = load_codec_model(use_gpu=codec_use_gpu, force_reload=force_reload)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 297, in load_codec_model
    model = _load_codec_model(device)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 253, in _load_codec_model
    model = EncodecModel.encodec_model_24khz()
  File "/home/vuaieo/.local/lib/python3.10/site-packages/encodec/model.py", line 279, in encodec_model_24khz
    state_dict = EncodecModel._get_pretrained(checkpoint_name, repository)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/encodec/model.py", line 262, in _get_pretrained
    return torch.hub.load_state_dict_from_url(url, map_location='cpu', check_hash=True)  # type:ignore
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/hub.py", line 746, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/http/client.py", line 1455, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.0/scripts/addons/Generative_AI-main/__init__.py", line 802, in execute
    preload_models(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 330, in preload_models
    _ = load_codec_model(use_gpu=codec_use_gpu, force_reload=force_reload)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 297, in load_codec_model
    model = _load_codec_model(device)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/bark/generation.py", line 253, in _load_codec_model
    model = EncodecModel.encodec_model_24khz()
  File "/home/vuaieo/.local/lib/python3.10/site-packages/encodec/model.py", line 279, in encodec_model_24khz
    state_dict = EncodecModel._get_pretrained(checkpoint_name, repository)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/encodec/model.py", line 262, in _get_pretrained
    return torch.hub.load_state_dict_from_url(url, map_location='cpu', check_hash=True)  # type:ignore
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/hub.py", line 746, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/home/vuaieo/Desktop/UPBGE/4.0/python/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>

and when trying to make many frames for video it gives me this error:

ae/diffusion_pytorch_model.safetensors not found
  0%|                                                                             | 0/100 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.0/scripts/addons/Generative_AI-main/__init__.py", line 667, in execute
    video_frames = pipe(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py", line 634, in __call__
    noise_pred = self.unet(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/unet_3d_condition.py", line 469, in forward
    sample = self.transformer_in(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/transformer_temporal.py", line 153, in forward
    hidden_states = block(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/attention.py", line 313, in forward
    attn_output = self.attn1(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 267, in forward
    return self.processor(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 743, in __call__
    hidden_states = F.scaled_dot_product_attention(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 646.00 MiB (GPU 0; 11.76 GiB total capacity; 7.71 GiB already allocated; 419.06 MiB free; 7.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.0/scripts/addons/Generative_AI-main/__init__.py", line 667, in execute
    video_frames = pipe(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/pipelines/text_to_video_synthesis/pipeline_text_to_video_synth.py", line 634, in __call__
    noise_pred = self.unet(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/unet_3d_condition.py", line 469, in forward
    sample = self.transformer_in(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/transformer_temporal.py", line 153, in forward
    hidden_states = block(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/attention.py", line 313, in forward
    attn_output = self.attn1(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 267, in forward
    return self.processor(
  File "/home/vuaieo/.local/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 743, in __call__
    hidden_states = F.scaled_dot_product_attention(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 646.00 MiB (GPU 0; 11.76 GiB total capacity; 7.71 GiB already allocated; 419.06 MiB free; 7.89 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

context_path_validate error: context.space_data.context not found (invalid keymap entry?)

i use nobara linux...

please help this is super amazing addon : )

**Comment by tin2tin** [comment] 2023-05-25 06:17
On Bark, did you first install this: https://git-scm.com/downloads ? I'm not on Linux, so I can't reproduce it. Try to see if something needs to be done differently when installing Bark on Linux: https://github.com/suno-ai/bark If you need to remove/install different versions of Python, then this add-on can be used: https://github.com/amb/blender_pip

When trying to make many frames, you're running out of VRAM. These processes are very memory intensive. As Blender gets unstable when running out of VRAM, restart it and start with much lower number of frames ex. 10 and 256x256, and work your way up from there, until you have reached values just before it runs out of VRAM.

**Comment by tin2tin** [comment] 2023-05-25 06:20
@vuaieo A Linux related question. Did you experience this, or can I close this Linux related bug report(it sounds like you're able to generate audio with audioLDM and shorter videos?): https://github.com/tin2tin/Generative_AI/issues/8

**Comment by vuaieo** [comment] 2023-05-25 08:54
hi no i didn not experience this i only got the errors that i showed T__T, well i got the git installed and for other i am too noob for that to understands all... the audioLDM somehow super sucks : ( but thanks for helps, this addon is super cool i hope it will get better cant wait for it : )

**Comment by tin2tin** [comment] 2023-05-25 09:30
Yes, audioLDM could need some improvements, however people are able to squeeze something good out of it. Google for prompts to use. 

As for Bark, you could try to use that add-on(Blender pip) I mentioned above to uninstall Bark, and first try "Install All Dependencies", and if that doesn't work, then uninstall it again, and use the git line mentioned on the Bark github site and install it using the pip add-on.

**Closed** 2023-06-02 14:49 UTC
